### ISSUE TITLE
GPU utilization is very low

### ISSUE THREAD

**Issue by clumsynope** [aigc-apps/EasyAnimate#64]
When I run sh scripts/train.sh for multi-machine and multi-card training, I find that the GPU utilization is very low, probably only about 50%. Is there any way to improve GPU utilization and enhance training efficiency?

**Comment by yunkchen** [comment]
try to increase dataloader_num_workers

**Comment by bubbliiiing** [comment]
Due to the fact that samplers need to be trained based on the height and width of images and videos, it is recommended to calculate the height and width of the data simultaneously during data loading when there are many machines.
![image](https://github.com/user-attachments/assets/bb698e58-2253-4b1e-b0e3-b47f662a13e8)

**Comment by bubbliiiing** [comment]
I will add this prompt to the subsequent Readme

**Comment by clumsynope** [comment]
ok, thank you.
